FROM pytorch/pytorch:2.4.0-cuda11.8-cudnn9-devel

RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub \
    && apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu2004/x86_64/7fa2af80.pub \
    && apt-get update \
    && DEBIAN_FRONTEND="noninteractive" apt-get install -y git ninja-build cmake build-essential

# Install MinkowskiEngine
RUN apt-get -y install libopenblas-dev nvidia-cuda-dev
ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 6.2 7.0 7.2 7.5 8.0 8.6 8.7 8.9 9.0"
ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"

RUN git clone --recursive "https://github.com/NVIDIA/MinkowskiEngine" \
    && cd MinkowskiEngine \
    && git checkout 02fc608bea4c0549b0a7b00ca1bf15dee4a0b228 \
    && python setup.py install --force_cuda --blas=openblas \
    && cd ..

RUN git clone https://github.com/robertod/SpatioTemporalSegmentation.git \
    && cd SpatioTemporalSegmentation \
    && pip install -r requirements.txt \
    && cd ..
